apiVersion: audit.k8s.io/v1
kind: Policy
rules:

  - level: None
    resources:
    - group: ""
      resources: ["secrets"]
    namespaces: ["kube-system"]

  - level: None
    users: ["system:kube-controller-manager"]
    resources:
    - group: ""
      resources: ["secrets"]

  - level: RequestResponse
    resources:
    - group: ""
      resources: ["secrets"]