---
apiVersion: v1
kind: Pod
metadata:
  name: super-secret
  namespace: development
spec:
  containers:
  - image: nginx
    name: demo-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged
  namespace: development
spec:
  containers:
  - image: nginx
    name: demo-pod
    securityContext:
      privileged: true
---
